[project]

fullname = "Corpus of Decisions: International Court of Justice"
shortname = "CD-ICJ"
author = "Seán Fobbe"



[license]

data = "Creative Commons Zero 1.0 Universal"
code = "GNU GPL v3"



[doi] # Digital Object Identifier (DOI)

data.concept = "10.5281/zenodo.3826444" # do not change
data.version = "10.5281/zenodo.10030647" # checked


software.concept = "10.5281/zenodo.3977176" # do not change
software.version = "10.5281/zenodo.10030648" # checked



[caseno] # Scope

begin = 1
end = 195
exclude = 2



[debug]

toggle = false
sample = 3 



[cores]

max = true # Whether to use maximum number of cores
number = 8 # Only if cores.max = false: number of cores to use.



[ocr]

dpi = 300



[download]

timeout = 600		# Download Timeout



[fig] # Knitr

format = [ "pdf", "png" ] 	# Figures: Output Format
dpi = 300     	 	# Figures: Resolution
align = "center"    	# Figures: Alignment in Reports



[freqvar] # Frequency Tables

ignore = ["date",
          "doc_id",
	  "text"]

