# Project

project.fullname = "Corpus of Decisions: International Court of Justice"
project.shortname = "CD-ICJ"
project.author = "Seán Fobbe"


# License

license.data = "Creative Commons Zero 1.0 Universal"
license.code = "MIT-0"


# Digital Object Identifier (DOI)

doi.data.concept = "10.5281/zenodo.3826444" # do not change
doi.data.version = "10.5281/zenodo.7876286"


doi.software.concept = "10.5281/zenodo.3977176" # do not change
doi.software.version = "10.5281/zenodo.7876287"


# Scope

caseno.begin = 1
caseno.end = 183
caseno.exclude = 2


# Debugging

debug.toggle = true
debug.sample = 3 


# Parallelization

cores.max = true # Whether to use maximum number of cores
cores.number = 8 # Only if cores.max = false: number of cores to use.


# OCR
ocr.dpi = 300


# Download
download.timeout = 600		# Download Timeout



# Knitr

fig.format = [ "pdf", "png" ] 	# Figures: Output Format
fig.dpi = 300     	 	# Figures: Resolution
fig.align = "center"    	# Figures: Alignment in Reports



# Frequency Tables

freqvar.ignore = ["date",
		  "doc_id",
		  "text"]

