version: "3.9"

services:
  cd-icj:
    container_name: cd-icj
    image: cd-icj:4.2.2
    tty: true
    volumes:
      - .:/cd-icj:z
      - ./etc/gitconfig:/etc/gitconfig:z
      - ./etc/magick-policy.xml:/etc/ImageMagick-6/policy.xml:z